# Generated by Django 5.0.1 on 2024-01-27 19:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('bus_id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Bus ID')),
                ('route_name', models.CharField(max_length=200, verbose_name='Route Name')),
                ('locations', models.TextField(verbose_name='Locations')),
            ],
            options={
                'verbose_name': 'Bus Route',
                'verbose_name_plural': 'Bus Routes',
            },
        ),
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200, verbose_name='User ID')),
                ('bus_id', models.CharField(max_length=200, verbose_name='Bus ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and Time')),
                ('bus_url', models.URLField(verbose_name='Bus Photo URL')),
                ('selfie_url', models.URLField(verbose_name='Selfie Photo URL')),
            ],
            options={
                'verbose_name': 'Ride',
                'verbose_name_plural': 'Rides',
                'ordering': ['-date_time'],
            },
        ),
    ]
