# Generated by Django 5.0.1 on 2024-01-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commuter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200, verbose_name='User ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('profile_url', models.URLField(verbose_name='Photo URL')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AddField(
            model_name='rides',
            name='caption',
            field=models.CharField(default='', max_length=200, verbose_name='Caption'),
        ),
    ]
