# Generated by Django 5.0.1 on 2024-01-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commuter', '0003_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='redeem_cost',
            field=models.IntegerField(verbose_name='Redeem Cost'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_logo',
            field=models.URLField(verbose_name='Sponsor Logo URL'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_name',
            field=models.CharField(max_length=200, verbose_name='Sponsor Name'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_url',
            field=models.URLField(verbose_name='Sponsor URL'),
        ),
    ]
