# Generated by Django 5.0.1 on 2024-01-28 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commuter', '0004_alter_sponsor_redeem_cost_alter_sponsor_sponsor_logo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sponsor',
            new_name='Sponsors',
        ),
    ]
